- hosts: terraform-airflow-iac
  tasks:
  - name: downlaod do docker compose
    shell: curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.2.2/docker-compose.yaml'
  - name: criando diretorios necessarios
    shell: mkdir ./dags ./logs ./plugins
  - name: config de arquivos
    shell: echo -e "AIRFLOW_UID=$(id -u)" > .env
  - name: inicialização do container
    shell: /usr/local/bin/docker-compose up airflow-init 
  - name: subindo os serviços
    shell: /usr/local/bin/docker-compose up -d